
export const GET_CUR_MOVEMENT_REQUEST_SUCCESS = '[AK][CUR_MOVEMENT] SUCCESS_REQUEST';
export const GET_CUR_MOVEMENT_SEND_REQUEST = '[AK][CUR_MOVEMENT] SEND_REQUEST';
export const GET_CUR_LIST_REQUEST_SUCCESS = '[AK][CUR_LIST] SUCCESS_REQUEST';
export const GET_CUR_LIST_SEND_REQUEST = '[AK][CUR_LIST] SEND_REQUEST';
export const GET_FILTER_CELL = '[AK][CUR_LIST_FILTER] FILTERED';

