
export const GET_CUR_MOVEMENT_REQUEST_SUCCESS = '[AK][SIDEBAR] SUCCESS_REQUEST';
export const GET_CUR_MOVEMENT_SEND_REQUEST = '[AK][SIDEBAR] SEND_REQUEST';
export const GET_CUR_LIST_REQUEST_SUCCESS = '[AK][APP] SUCCESS_REQUEST';
export const GET_CUR_LIST_SEND_REQUEST = '[AK][APP] SEND_REQUEST';
export const GET_FILTER_CELL = '[AK][SEARCH] FILTER_CELL';

export const ADD_CUR_TO_FAVORITE = '[AK][FAVORITE] ADD_CUR_TO_FAVORITE';
export const REMOVE_CUR_FROM_FAVORITE = '[AK][FAVORITE] REMOVE_CUR_FROM_FAVORITE';

export const GET_CUR_INFO_SEND_REQUEST = '[AK][FAVORITE] GET_CUR_INFO_SEND_REQUEST';
export const GET_CUR_INFO_REQUEST_SUCCESS = '[AK][FAVORITE] GET_CUR_INFO_REQUEST_SUCCESS';

export const SHOW_FAVORITE_CUR_MOVEMENT = '[AK][FAVORITE] SHOW_FAVORITE_CUR_MOVEMENT';
export const SAVE_CUR_MOVEMENT = '[AK][CURRENCIES] SAVE_CUR_MOVEMENT';
export const REMOVE_CUR_INFO_FROM_FAVORITE = '[AK][FAVORITE] REMOVE_CUR_INFO';
export const REMOVE_CUR_MOVEMENT_FROM_FAVORITE = '[AK][FAVORITE] REMOVE_CUR_MOVEMENT';

export const SET_DESTINATION_CUR_INFO = '[AK][CONVERTER] SET_DESTINATION_CUR_INFO';
export const SET_DESTINATION_VALUE = '[AK][CONVERTER] SET_DESTINATION_VALUE';

export const SET_START_DATE = '[AK][DATEPICKER] SET_START_DATE';
export const SET_END_DATE = '[AK][DATEPICKER] SET_END_DATE';

export const SET_SELECTED_CUR_INFO = '[AK][CONVERTER] SET_SELECTED_CUR_INFO';
