
export const GET_CUR_MOVEMENT_SUCCESS = '[AK][CUR_MOVEMENT] SUCCESS_REQUEST';
export const GET_CUR_LIST_SUCCESS = '[AK][CUR_LIST] SUCCESS_REQUEST';
export const GET_FILTER_CELL = '[AK][CUR_LIST_FILTER] FILTERED';